version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  aws-s3: circleci/aws-s3@3.0.0
  browser-tools: circleci/browser-tools@1.1
  node: circleci/node@5.1.0

executors:
  my-executor:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium

jobs:
  my-job:
    executor: my-executor
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: cat /proc/cpuinfo
      - run: gcc --version
      - run: command -v ruby
      - run: command -v bundler
      - run: command -v node
      - run: rbenv versions
      - run: nvm ls
      - run: ruby --version
      - run: gem --version
      - run: bundler --version
      - run: node --version
      - run: nvm --version
      - run: rbenv install 2.7.8
      - run: nvm install --lts=gallium

workflows:
  build_and_test:
    jobs:
      - my-job
