version: 2.1

executors:
  my-executor:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium

jobs:
  my-job:
    executor: my-executor
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"

workflows:
  build_and_test:
    jobs:
      - my-job
