version: 2.1

executors:
  my-executor:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium

jobs:
  my-job:
    executor: my-executor
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: cat /proc/cpuinfo
      - run: gcc --version
      - run: command -v ruby
      - run: command -v bundler
      - run: command -v node

workflows:
  build_and_test:
    jobs:
      - my-job
